Update setupkali

diff --git a/setupkali b/setupkali
--- a/setupkali
+++ b/setupkali
@@ -1,56 +1,66 @@
-#!/bin/bash
-# Needs work ... error handling and confirmations
-# kali setup and required files
-# to setup KALI linux to be useable
-# needs to run with sudo permissions
-# use format 'sudo ./script.sh
-# recommendations of Rana Nadir @clubcleaver
-echo -e "needs SUDO  priveleges ... Please enter your password:\n"
-sudo apt update
-apt -y full-upgrade
-apt -y install locate
-apt -y install golang-go
-apt -y install gcc-multilib 
-apt -y install mousepad
-apt -y install flameshot
-apt -y install proftpd
-apt -y install rlwrap
-# apt -y install bloodhound
-# bloodhound uses 'neo4j' database to operate 
-# to setup neo4j use ' neo4j console '
-# comment the following section to setup manually
-# echo -e "\n\n Remember to open the link and stup a password for neo4j"
-# neo4j console
+#! /bin/bash
+if [ $EUID -ne 0 ]
+then
+	echo "ERROR: Need Sudo Permissions"
+	exit
+else
+	clear
+	echo -e "\n\n\nHELLO ${SUDO_USER}\n\n\nLETS SETUP OUR DEBIAN LINUX\n\n\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
+	userHome=$(eval echo ~${SUDO_USER})
+#	echo $userHome
 
-#may need to include in /etc/apt/sources.list
-# " deb http://http.kali.org/kali kali-rolling main contrib non-free "
-apt -y install python-pip
-apt -y install python3-pip
+	# Spinner Function
+	spinner () {
+		pid=$!
+		i=0
+		while kill -0 $pid 2>/dev/null
+		do
+			i=$(( (i+1) %4 ))
+			printf "\r${spin:$i:1}"
+			sleep 0.1
+		done
+	}
 
-# making directories for oscp labs
-mkdir -p ~/labs/pub ~/labs/vpn ~/tools/scripts ~/tools/enum
-cd ~/tools/enum/ && wget https://github.com/PowerShellMafia/PowerSploit/raw/master/Recon/PowerView.ps1 -O powerview.ps1
-cd
-cd ~/tools/scripts/
-wget https://github.com/clubcleaver/tools/raw/main/envset.sh -O envset
-chmod 777 envset
-cp envset /bin/
-wget https://github.com/clubcleaver/tools/raw/main/linum.sh -O linum
-chmod 777 linum
-cd
-sudo cp /home/kali/tools/Invoke-Kerberoast.ps1 ~/tools/invoke-kerberoast.ps1
-cd ~/tools
-wget https://github.com/caday00/mimikatz2.1.1/archive/refs/heads/master.zip -O oldmimi.exe
+	# Setup TMUX Environment
+	tmux_setup () {
+		echo -e "Setting Up TMUX\n"
+		cd $userHome
+		touch .tmux.conf
+		echo -e "set -g status-style bg=Black\nset -g base-index 1\nbind-key -n M-w select-pane -U\nbind-key -n M-a select-pane -L\nbind-key -n M-s select-pane -D\nbind-key -n M-d select-pane -R" > .tmux.conf
+	}
+	tmux_setup
 
-## write result description:
-clear
-echo -e "\n\nInstalled the following on KALI: \n"
-echo -e "locate command\nGolang\ngcc libraries for 32bit compilations\nmousepad \nflameshot \nproftpd \nbloodhound \npython pip vesions 2 and 3 \n"
-echo -e "\n\nMade directories for tools, scripts and vpn"
-echo -e "\nfind:\nlinum in ~/tools/scripts/\npowerview in ~/tools/enum/"
-echo -e "\n commad:\nenvset was downloaded and copied to '/bin/' and is ready to use "
+	# Setting Up Debian Linux
+	echo -e "UPDATING APT: \n"
+	sudo apt-get update -y 1>/dev/null &
+	spinner
+	sudo apt-get upgrade -y 1>/dev/null &
+	spinner
 
+	# Setting Up Microsoft Repo for VS Code.
+	sudo apt-get install wget gpg -y 1>/dev/null
+	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
+	sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
+	sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
+	rm -f packages.microsoft.gpg
 
-#mkdir /ftpuser
-#groupadd ftpuser
-#useradd 
+	# List of Packages to install
+	LIST=("plocate" "gcc-multilib" "golang-go" "flameshot" "rclone" "terminator" "nodejs" "npm" "code" "python-pip" "python3-pip" "" )
+	echo -e "Installing Packages: \n"
+
+	# Installing Package List including VS CODE.
+	spin='-\|/'
+
+	# Looping Over Array to install
+	for p in ${LIST[@]}
+	do
+		sudo apt-get install -y  $p 1>/dev/null && echo -e "\nPackage ${p} Install Successfully\n" || echo -e "\nError: Error While Installing ${p}\n"
+		spinner
+	done
+
+	# Download Nerd Fonts
+	echo -e "Downloading Nerd Fonts\n"
+	wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/EnvyCodeR.zip -P $userHome/Downloads/. 1>/dev/null
+	wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hermit.zip -P $userHome/Downloads/. 1>/dev/null
+
+fi
